### PR TITLE
Adding and integrating mocap_pose node

### PR DESCRIPTION
**Pull request by sergey-unikie**
It's still a preliminary pull-request, please do not merge it yet.
Review and comment please!

### CODE REVIEW

**Comment by jnippula** [comment]
Looks good. I guess next thing would be at least to add systemd service file to start up the mocap node. Not sure how to trigger the node start. The indoor_pos node starts when HTC vive tracker module is powered on, but there is no such external drone module for mocap, so something else should be used. Maybe it could be always started, but the node would be kind of idle state until it gets connected to the mocap server, so something like that..

**Comment by maseabunikie** [comment]
> Looks good. I guess next thing would be at least to add systemd service file to start up the mocap node. Not sure how to trigger the node start. The indoor_pos node starts when HTC vive tracker module is powered on, but there is no such external drone module for mocap, so something else should be used. Maybe it could be always started, but the node would be kind of idle state until it gets connected to the mocap server, so something like that..

Some information which I got from Johannes.
The drone will have another WLAN interface (TP-Link USB dongle) which will be connected to the mocap's own network. We should start the node when this WLAN device is detected and interface link is up. Also we should make this node to talk only to the mocap WLAN interface.

**Comment by sergey-unikie** [comment]
@jnippula @maseabunikie Can you please review again, and tell what is still missing? 
Please double-check systemd stuff, I've just copy-pasted and edited that  
Here few more questions:
1. @jnippula Do we need to control `mocap_pose` in the same way as it's done in `indoor_pos`? 
2. How to make TP Link module to connect automatically to some specific WiFi network? I need help with that

**Comment by sergey-unikie** [comment]
@jnippula  @jlaitine @maseabunikie   
Guys, please review again, I think it's now ready for merging.
One problem is that `main` of `fog_sw` points to very old version of `systemd` repo, such that I've got conflict here.

**Comment by jnippula** [comment]
> @jnippula @maseabunikie Can you please review again, and tell what is still missing?
> Please double-check systemd stuff, I've just copy-pasted and edited that

Systemd file looks ok. However, we may need to change the Requires/After defines as we may not need to set mesh net up before other ros nodes that does not need to communicate via mesh.

> Here few more questions:
> 
> 1. @jnippula Do we need to control `mocap_pose` in the same way as it's done in `indoor_pos`?

Not sure what do you mean about this, but in general the mocap should handle the gps messages in the same way than indoor_pos does. Indoor_pos start is triggered by vive tracker usb connection, so that can't be done in the same way. Unless the TPlink receiver attach event could be used for that purpose.

> 2. How to make TP Link module to connect automatically to some specific WiFi network? I need help with that

Need to specify network configuration for that network adapter, if not yet done. Then the connection is established via that adapter in case the ip we are connecting to is defined to be routed via that interface. Let's check that on next week.

**Pull request closed without merging**
